// <auto-generated />
namespace OnionMessenger.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddedMaxLengthofallStringcolumns20viaFluentApi : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddedMaxLengthofallStringcolumns20viaFluentApi));
        
        string IMigrationMetadata.Id
        {
            get { return "201903311430311_Added MaxLength of all String columns = 20, via FluentApi"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
